version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: jokes_nginx
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    networks:
      - gl-package

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: jokes_php
    volumes:
      - ./:/var/www/html
    networks:
      - gl-package

networks:
  gl-package:
    name: gl-package
